# General Jekyll Config
url: http://eeti3084.github.io/
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Jekyll SEO Tag plugin
title: Data Science Journal
description: A Data Science Journal by shanmukha eeti, a Junior Data Scientist in Hong Kong. From Python, Numpy, Pandas, Matplotlib, Seaborn, R, ggplot, dplyr, to SQL, from Data Wrangling, Data Visualization, to Machine Learning, this is a blog to share her dedicated journey in learning Data Science.
author: shanmukha eeti

twitter:
  username: shanmukhaa
